name: release win7

permissions:
  contents: write

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build_release_win7:

    name: build_release for win7
    runs-on: windows-2019

    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set release date
        shell: bash
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      # - name: cleanup
      #   run:  |
      #     Get-Package "*python*" | Uninstall-Package

      # - name: install custom py
      #   shell: bash
      #   run: |
      #     curl -kLSs https://github.com/adang1345/PythonWin7/raw/refs/heads/master/3.10.16/python-3.10.16-embed-amd64.zip -o python.zip
      #     unzip python.zip

      - uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      # - name: pip audit
      #   shell: bash
      #   run: |
      #     python3 -m pip install pip-audit
      #     pip-audit -r requirements.txt 

      - name: Build
        shell: bash
        run: |

          python -m venv easy_mtr

          easy_mtr/Scripts/activate

          python -m pip install -r requirements.txt 
          
          find . -iname "*tcl"

          cd src
          pyinstaller -F easy_multitrack_recorder.py --add-data "assets/*;assets" --add-data "api-ms-win-core-path-l1-1-0.dll;." --icon "assets/icon.ico" -n easy_multitrack_recorder_${{ runner.os}}Legacy

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: EasyMultitrackRecorder ${{ runner.os }}Legacy
          tag_name: ${{ runner.os }}Legacy.${{ env.RELEASE_DATE }}
          files: src/dist/*
