name: build linux

on:
  push:
    branches:
      - "main"

  workflow_dispatch:


jobs:
  build:
    name: build linux
    runs-on: windows-latest
    timeout-minutes: 20
    steps:          
                
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: pypa/gh-action-pip-audit@v1.1.0 
        with:
          inputs: requirements.txt
          local: true

      - run: |
          python -m venv easy_mtr
          . easy_mtr/bin/activate
          python -m pip install -r requirements.txt
          cd src
          pyinstaller -F easy_multitrack_recorder.py --add-data "assets/*:assets" --icon "assets/icon.ico"

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: src/dist/easy_multitrack_recorder*