name: release

permissions:
  contents: write

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
    
      - name: set NOW
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> "$GITHUB_ENV"


      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: pypa/gh-action-pip-audit@v1.1.0 
        with:
          inputs: requirements.txt
          local: true

      - run: |
          python -m venv easy_mtr
          . easy_mtr/bin/activate
          python -m pip install -r requirements.txt
          cd src
          pyinstaller -F easy_multitrack_recorder.py --add-data "assets/*:assets" --icon "assets/icon.ico"
  

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: linux
          tag_name: $NOW
          files: src/dist/*