name: release

permissions:
  contents: write

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build_release:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    name: build_release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set release date (non windows)
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: set release date (windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          chcp 65001 #set code page to utf-8
          $now = Get-Date -Format yyyy-MM-dd
          echo ("RELEASE_DATE=" + $now) >> $env:GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: "3.7.17"

      # - uses: pypa/gh-action-pip-audit@v1.1.0
      #   with:
      #     inputs: requirements.txt
      #     local: true

      - name: Build non windows
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m venv easy_mtr
          . easy_mtr/bin/activate
          python -m pip install -r requirements.txt 
          
          cd src
          pyinstaller -F easy_multitrack_recorder.py --add-data "assets/*:assets" --icon "assets/icon.ico" -n easy_multitrack_recorder_${{ runner.os}}

      - name: Build windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m venv easy_mtr
          easy_mtr\Scripts\activate
          python -m pip install -r requirements.txt
          
          cd src
          pyinstaller -F easy_multitrack_recorder.py --add-data "assets/*;assets" --icon "assets/icon.ico"  -n easy_multitrack_recorder_${{ runner.os}}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: EasyMultitrackRecorder ${{ runner.os }}
          tag_name: ${{ runner.os }}.${{ env.RELEASE_DATE }}
          files: src/dist/*
